{% set name = "murmurhash" %}
{% set version = "1.0.5" %}
{% set sha256sum = "98ec9d727bd998a35385abd56b062cf0cca216725ea7ec5068604ab566f7e97f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: true  # [win32 or linux32]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes  # [win and py<35]
    - python
    - pip
    - setuptools

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - murmurhash
    - murmurhash.mrmr

about:
  home: https://github.com/explosion/murmurhash/
  license: MIT
  license_file: LICENSE
  summary: Cython bindings for MurmurHash2

extra:
  recipe-maintainers:
    - rmax
    - ines
    - honnibal
    - adrianeboyd
